(function () {
  'use strict';

  angular.module('exdFrontendApp').directive('smachEditor', [
    'backendInterfaceService',
    'pythonCodeHelper',
    'documentationURLs',
    'STATE',
    '$timeout',
    function (backendInterfaceService,
              pythonCodeHelper,
              documentationURLs,
              STATE,
              $timeout) {
      return {
        templateUrl: 'views/esv/smach-editor.html',
        restrict: 'E',
        scope: {
          control: '='
        },
        link: function (scope, element, attrs) {

          scope.STATE = STATE;
          scope.stateMachines = [];
          var ScriptObject = pythonCodeHelper.ScriptObject;
          var addedStateMachineCount = 0;

          documentationURLs.getDocumentationURLs().then(function(data) {
            scope.backendDocumentationURL = data.backendDocumentationURL;
          });

          scope.refreshLayout = function(editor) {
            // This updates the layout of the editor also onLoad
            // Just a editor.refresh() does not work here, so we set a callback on the first "change" event
            // and remove the listener afterwards
            var r = function() {
              editor.refresh();
              editor.off("change", r);
            };
            editor.on("change", r);
          };

          scope.control.refresh = function () {
            backendInterfaceService.getStateMachines(
              function (response) {
                _.forEach(response.data, function(code, id) {
                  var stateMachine = new ScriptObject(id, code);
                  stateMachine.name = scope.getStateMachineName(id);
                  // If we already have local changes, we do not update
                  var sm = _.find(scope.stateMachines, {'id':  id});
                  var found = angular.isDefined(sm);
                  if (found && !sm.dirty)
                  {
                    sm = stateMachine;
                  } else if (!found) {
                    scope.stateMachines.unshift(stateMachine);
                  }
                });
              });
          };

          scope.update = function(stateMachine) {
            backendInterfaceService.setStateMachine(
              stateMachine.id,
              stateMachine.code,
              function(){
                stateMachine.dirty = false;
                stateMachine.local = false;
              });
          };

          scope.onStateMachineChange = function (stateMachine) {
            stateMachine.dirty = true;
          };

          scope.create = function(code) {
            var count = addedStateMachineCount;
            var defaultCode = 'import smach_ros\n'+
              'from smach import StateMachine\n'+
              'from rosgraph_msgs.msg import Clock\n\n'+

              'def timeline_condition(user_data, time):\n'+
              '    return time.clock.secs < 20\n\n'+

              'FINISHED = \'FINISHED\'\n'+
              'ERROR = \'ERROR\'\n'+
              'PREEMPTED = \'PREEMPTED\'\n\n'+

              'sm = StateMachine(outcomes=[FINISHED, ERROR, PREEMPTED])\n\n'+

              'with sm:\n'+
              '    StateMachine.add(\n'+
              '     "timeline_condition",\n'+
              '     smach_ros.MonitorState(\'/clock\', Clock, timeline_condition),\n'+
              '     transitions = {\'valid\': \'timeline_condition\',\n'+
              '                    \'invalid\': FINISHED,\n'+
              '                    \'preempted\': PREEMPTED}\n'+
              '    )\n';

            code = code ? code : defaultCode;
            var id = scope.generateID(count);
            var stateMachine = new ScriptObject(id, code);
            stateMachine.dirty = true;
            stateMachine.local = true;
            stateMachine.name = scope.getStateMachineName(id);
            scope.stateMachines.unshift(stateMachine);
            addedStateMachineCount = addedStateMachineCount + 1;
            return stateMachine;
          };

          scope.delete = function(stateMachine) {
            var index = scope.stateMachines.indexOf(stateMachine);
            if (stateMachine.local) {
              scope.stateMachines.splice(index, 1);
            } else {
              backendInterfaceService.deleteStateMachine(stateMachine.id,
                function() {
                  scope.stateMachines.splice(index, 1);
                }
              );
            }
          };

          scope.getStateMachineName = function(id) {
            var stateMachineIDRegExp = /^(statemachine_[0-9]+)_[0-9]+_front\-end_generated$/gm;
            var matches = stateMachineIDRegExp.exec(id);
            if (matches) {
              // The state machine ID was generated by the front-end.
              // Returns a simplified string ID of the form statemachine_<int>
              return matches[1];
            }
            // The state machine ID was originally set in the back-end.
            // Hopefully, it is a meaningful name
            return id;
          };

          scope.generateID = function(count) {
            return 'statemachine_' + count + '_' + Date.now() + '_front-end_generated';
          };

          scope.save = function (stateMachine) {
            var file = new Blob([stateMachine.code], {type: "plain/text", endings: 'native'});
            var button = angular.element(document.querySelector('#save-state-machine-to-file-' + stateMachine.id));
            button.attr("href", URL.createObjectURL(file));
          };

          scope.loadStateMachine = function(file) {
            if (file && !file.$error) {
              var textReader = new FileReader();
              textReader.onload = function(e) {
                $timeout(function() {
                  var code = e.target.result;
                  var sm = scope.create(code);
                  scope.update(sm);
                });
              };

              textReader.readAsText(file);
            }
          };
        }
      };
    }
  ]);

})();
